# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-runner:
    # The type of runner that the job will run on
    runs-on: [self-hosted]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkoutrepository
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Print system details
        shell: powershell
        run: |
          echo "Hello World"
          echo "Runner 29832-438562 self-hosted Windows X64"
     
      - name: Test PowerShell Execution
        shell: powershell
        run: |
          Write-Host "Successfully connected and executed PowerShell on runner 29832-438562!"
